### ISSUE TITLE
All questions: Graphic Design - Font Size

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#10]
Feedback from qispsk@gmail.com : The font size here seems significantly smaller than the previous versions of the artwork. Any way that the font size of the answers can be increased?

 [Link to buddybuild feedback from build 7](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=56dd2903c042780100e148c9&bnum=7)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/56dcafa10b8e3e0100d226ce/36aec9fc-acee-42cd-827f-70ba77b63e74.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>7</td></tr><tr><td>Device type</td><td>LG-H324</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 786px</td></tr><tr><td>Battery</td><td>76% Unplugged</td></tr><tr><td>Memory free</td><td>243 MB / 711 MB</td></tr></table>

**Comment by adrianq** [comment]
@QISPSK As I said in my previous comment, the texts are embedded in the image. If in the new artwork the font size is bigger it will look much bigger. Not too much we can do in this sense... As you can see the images try to fit in the device screen without squeezing.

**Comment by adrianq** [comment]
I leave it open so that @gtrsmith @rodmelia can also comment the card if they want to. Although I think they were already aware of this issue

**Comment by cristinaelle** [comment]
@QISPSK : as you know at the moment users click on pictures and the Khmer scripts are embedded in pictures (image + Khmer scripts). please, make note of all the things that you want the graphic designer to work on, so that we'll submit these comments to her. 
In the future we'll change this approach, so the graphic designer doesn't get crazy in changing the font size and the developers and the users can easily adapt the font size at their liking while the image in the background stays the same.

**Comment by QISPSK** [comment]
@cristinaelle The font size and the ordering of the items on the drug selection screen are the only two outstanding issues that the team has identified that need to be addressed by the graphic designer. The attached document gives an idea of what we are looking for in terms of both font size and drug order. Let us know if you have any questions.

[Update QIS App_11.02.16 (2).pdf](https://github.com/EyeSeeTea/SurveillanceCambodiaApp/files/164344/Update.QIS.App_11.02.16.2.pdf)

**Comment by gtrsmith** [comment]
I will address with graphic designer.
