### ISSUE TITLE
OU ban system broken

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceCambodiaApp#101]

**Comment by QISPSK** [comment]
@ifoche Not entirely sure what this issue, but going to assume it's all fixed up? Anyway we can test this here?

**Comment by ifoche** [comment]
@QISPSK yes, it's the OU ban system. This system was introduced long time ago in the release to prevent from a user abuse. So if somebody tries to send more than 30 surveys in an hour, the app closes the OU and no more data can be sent to that OU, so only an admin can reopen it, by removing the close date from the server. If it's properly working, sending 31 in less than an hour would make the test.

**Comment by QISPSK** [comment]
@ifoche Tested and it is properly working, thanks! Marked as "Done."
