### ISSUE TITLE
Multi-user login issue

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceCambodiaApp#103]

**Comment by ifoche** [comment]
@QISPSK sorry but we've detected we introduced a bug on last release affecting the login user. In last Login Screen refactor, somehow we stop using the hardcoded common user to download the OUs and start using the username that you enter through the Login screen. This have obvious consequences if the username you use does not have access to the OUs you need to upload data to, or if that username receives OU for which the common user in the server is not allowed to upload data. Please accept my apologizes for this bug, we're now solving it and we will generate a new release today.

**Comment by ifoche** [comment]
@QISPSK  sorry for the inconveniences. The release that's now being generated have this OU problem solved. Please let me know if you find any further problem

**Comment by QISPSK** [comment]
@ifoche Not sure how to test this, but will take your word and assume it's done. We're still running into issues with the OU limit in DHIS2, but it sounds like @josemp10 is working on a script to overcome this issue until we upgrade to 2.25. Moved this issue to Done.
