### ISSUE TITLE
qispsk@gmail.com on build #50: Like the new tab names that match HNQIS! Can we change the…

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#104]
Feedback from qispsk@gmail.com : Like the new tab names that match HNQIS! Can we change the far right one to just "Assess?"

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/5837295e5399290100e94662/c9ef858d-1407-4ab8-8bb6-90233507ede9.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Mon Nov 28 2016 03:58:54 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>50</td></tr><tr><td>Device type</td><td>LG-X210</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 782px</td></tr><tr><td>Battery</td><td>50% Unplugged</td></tr><tr><td>Memory free</td><td>504 MB / 968 MB</td></tr></table>

 [Link to buddybuild feedback from build 50](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=583bab7e39372d0100b7be36&bnum=50)

**Comment by ifoche** [comment]
@QISPSK Sure! we'll include this change in the release we're about to generate with the fix to the actionbar bug

**Comment by ifoche** [comment]
We've just launched a new release with last bugfixing. Please let me know if you find any other bug.

**Comment by QISPSK** [comment]
@ifoche It looks like the newest build changed the tab names back to "Unsent," "Sent," and "Monitoring." Not a major change, but would be nice to keep this consistent with HNQIS *though "Sent" isn't really an "Improve" module...)

**Comment by ifoche** [comment]
@QISPSK sorry, I think I misunderstood your requirement. So which tab names would you prefer for next build? Here some options that sound good to me:
- UNSENT | SENT | MONITOR
- ASSESS | SENT | MONITOR ?
- ASSESS | REVIEW | MONITOR ?

**Comment by QISPSK** [comment]
@ifoche After a quick survey of opinions around the office, it sounds like we should just keep it the same given that we have trained on this already. Sorry for the confusion - thanks!

**Comment by ifoche** [comment]
No problem. So I move it to "Done" or you mean change it back to
ASESSS - ACTIVE | IMPROVE | MONITOR?

**Comment by ifoche** [comment]
ok, I see you've moved it to done :)
