### ISSUE TITLE
qispsk@gmail.com on build #50: Is it possible to show the synced OU at the top here as it…

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#105]
Feedback from qispsk@gmail.com : Is it possible to show the synced OU at the top here as it was in previous builds? Very minor so if its too much work, no worries, but it was helpful in quickly figuring out which phone is which.

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/5837295e5399290100e94662/ff0b91da-c892-4b6e-83f6-881052f7c30f.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Mon Nov 28 2016 04:02:36 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>50</td></tr><tr><td>Device type</td><td>LG-X210</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 782px</td></tr><tr><td>Battery</td><td>48% Unplugged</td></tr><tr><td>Memory free</td><td>490 MB / 968 MB</td></tr></table>

 [Link to buddybuild feedback from build 50](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=583bac5c06ae220100921a23&bnum=50)

**Comment by ifoche** [comment]
Sorry, this is a collateral damage of a code refactor we made recently. We're solving it now, and we will generate a new release once finished.

**Comment by QISPSK** [comment]
@ifoche Seems to be fixed in BB51, moved issue to "Done"
