### ISSUE TITLE
Incorrect Translations - Review Screen

### ISSUE THREAD

**Issue by QISPSK** [EyeSeeTea/SurveillanceCambodiaApp#109]
![image](https://cloud.githubusercontent.com/assets/17549893/25211534/dbed3eee-25af-11e7-92df-c9f81c21e1ac.png)
![image](https://cloud.githubusercontent.com/assets/17549893/25211567/f9bee90e-25af-11e7-98e8-64229b2a8c07.png)

1.	ផ្លាស្មូដ្យូម វីវ៉ាក់ (Pv) includes an extra “ផ” character at the beginning

2.	ចំរុះ (Mixed) includes an extra apostrophe at the end

3.	Spacing on ធ្វើការបញ្ជូន in the question needs to be slightly larger to capture the “ូ” vowel at the bottom

4.	សង្ស័យបរាជ័យក្នុងការព្យាបាល or “treatment failure” seems to be spelled incorrectly

**Comment by ifoche** [comment]
@QISPSK I think most of the changes you ask for here you can directly do it yourself in POEditor.  

For question titles, you can [search for Question_Title](https://poeditor.com/projects/po_edit?order=&filter=&id=50144&id_language=27&search=Question_Title) on POEditor, while for the options, you can [search for Option_Text](https://poeditor.com/projects/po_edit?order=&filter=&id=50144&id_language=27&search=Option_Text)
Re the space you need us to make larger, would you mind if we add that padding to all questions? If that's the case, it would be a really quick fix.

**Comment by QISPSK** [comment]
@ifoche is that something you can give qispsk@gmail.com access to, or do we already have access?

As for padding, as long as it is just enough to make the vowel visible, I think it's fine to add it to all questions.

**Comment by ifoche** [comment]
@QISPSK, you're right, you didn't have access. I've just added you as a contributor to Central Khmer and English languages with that email. Please let me know if you have any problem using it.

**Comment by QISPSK** [comment]
@ifoche  Fixed in POeditor, you can go ahead and add the required space

**Comment by ifoche** [comment]
Thanks! we will incorporate it into next release

**Comment by QISPSK** [comment]
![screenshot_2017-05-02-09-51-55](https://cloud.githubusercontent.com/assets/17549893/25602720/5c122494-2f20-11e7-879a-965ab18dc596.png)

@ifoche, Translations appear to be fixed, however, the introduction of spacing has thrown off the review screen. Any way that the spacing could just be applied to question text? Also, could it be reduced to the point where it just allows the review screen "ូ" to be visible? The current padding is quite large.

**Comment by ifoche** [comment]
@QISPSK making the spacing variable depending on the size of the text would be much more difficult than just including a fix padding. We will reduce it to the point that "ូ" gets visible, but without so many space. However if you have a graphic editor app and you want to share a mockup of what you have in mind, we would really appreciate it.

**Comment by QISPSK** [comment]
![review screen spacing](https://cloud.githubusercontent.com/assets/17549893/25646151/b8e6bfda-2fdf-11e7-8d32-c631ab01c569.png)

@ifoche, isn't variable spacing already included to some extent given the ability to adjust question text sizes? If not, it is likely something we should consider down to the road to ensure text sizes, question boxes, line breaks, and leading remain consistent in later builds.

Regardless, attached is an ideal image of sizes for the question box, question text, answer boxes, and answer text. I think if you simply add padding to the point where the "ូ" character is visible, all the other question boxes should work fine (as, I believe, this is the "tallest" question). Let us know if you need anything else. Thanks!

**Comment by ifoche** [comment]
@QISPSK the padding is not attached to the font size, because it's the text component what's adapting, but the padding belongs to the upper container. Making that change is not something that should take too much time, however, but I think like you, that only providing the minimum padding for showing the "ូ" character would probably make the trick. We will give a try to adjust the paddings to the image that you attached for this build, and then decide if we want to go for adaptative paddings...would that work for you?

**Comment by QISPSK** [comment]
@ifoche, yep, that sounds great on our end, let us know how it goes.
