### ISSUE TITLE
Treatment Amounts - Review Screen

### ISSUE THREAD

**Issue by QISPSK** [EyeSeeTea/SurveillanceCambodiaApp#110]
![image](https://cloud.githubusercontent.com/assets/17549893/25211612/2be8fc30-25b0-11e7-858e-bea99c529eac.png)

Is it possible to change the ACT review screen answers to pill quantity instead of weight/age banding? I.e., instead of “5 – 10 Years, 19 – 30 kg” it would instead say “4.5 pills”

**Comment by ifoche** [comment]
You can do it yourself changing it in POEditor. As said in #109 you can [search for Option_Text](https://poeditor.com/projects/po_edit?order=&filter=&id=50144&id_language=27&search=Option_Text) in POEditor and you'll find the options that you want to change.

**Comment by QISPSK** [comment]
@ifoche Fixed in POEditor

**Comment by ifoche** [comment]
Thanks! we will incorporate it into next release

**Comment by QISPSK** [comment]
@ifoche I forgot to update the text in POEditor for the English translations as well! Should be all fixed now

**Comment by ifoche** [comment]
@QISPSK no problem, we'll incorporate them for the next build

**Comment by QISPSK** [comment]
@ifoche English changes don't appear to have been incorporated into build 57

**Comment by ifoche** [comment]
Sorry, my fault, I simply forgot to add them in this build. We'll create a new build with them
