### ISSUE TITLE
Demo Mode Toggle?

### ISSUE THREAD

**Issue by QISPSK** [EyeSeeTea/SurveillanceCambodiaApp#112]
![image](https://cloud.githubusercontent.com/assets/17549893/25211676/8578a0c0-25b0-11e7-9b5a-32e4f46ada2e.png)

Is it possible to change “Run in Demo Mode” to a toggle so if providers accidently select this option, they can easily switch back to their OU?

**Comment by ifoche** [comment]
If it's about avoiding clicking by mistake, then maybe we could add a confirmation pop-up and that would be a very quick fix. 

If you really prefer the toggle option, that would be a bigger change, because currently, we're deleting the DB on any login to new OU so we avoid anyone that started filling in the data with an OU to finally change his mind and send to another one. That means we would need to change that (and test it properly) or keep 2 different OUs at a time (the demo OU and the user selected one). 

I'm not saying it's not feasible but would take much more time than the first option. I've configured label according to option 2.

**Comment by QISPSK** [comment]
@ifoche @rbeccapotter  The complexity makes sense... 

There are definite concerns about the item being selected accidentally which would necessitate a support staff member going to visit the provider to re-setup their OU (this is assuming that the provider knows that they have selected demo mode, if not, the app would appear to work as intended though we wouldn't be receiving any of the data).

As initially stated, the team here doesn't see a ton of value in demo mode given that we use test OUs when demonstrating the app to partners/CNM/etc. which also allows us to view the data directly in DHIS2 right after it is sent. I think there are three potential fixes we could implement: 

1. Remove the feature entirely
2. Keep the feature, but hide it behind a password of some sort
3. Keep the feature and add a popup

We would lobby for number one as the threat it poses among providers is too high to justify the limited benefit in country. However, the feature is useful on a regional level when showing off the application to donors/partners/etc. How complex would it be do do option two? 

Option three would likely be last resort. While a popup would hopefully deter some, we're not confident that it would be enough to prevent frequent switches to demo mode that would be near impossible to track from the data in DHIS2.

Thoughts?

**Comment by rbeccapotter** [comment]
@QISPSK If it doesn't make operational sense to have a demo mode, don't feel the need to keep it just for the sake for regional demo-ing. We can workaround by using test org units and demo user.

**Comment by ifoche** [comment]
What about including "Run in demo mode" only when "Developers options" setting is activated? Would that solve the issue?

**Comment by QISPSK** [comment]
@ifoche that would be a good way to "hide" it, but we're not sure it is effective enough. Would it be possible to come up with hour estimate for the removal of the feature entirely?

If it is quite difficult to do, we may just want to hide it under "developers options," but we think removing it entirely would be the safest way to proceed.

**Comment by ifoche** [comment]
Hi @QISPSK disabling the demo mode is quite easy. Do you want us to include it for this release?

**Comment by ifoche** [comment]
changed the complexity label to represent the effort for removing the demo mode

**Comment by QISPSK** [comment]
@ifoche Yes please. I've moved it into the "Ready" column.
