### ISSUE TITLE
Negative/Not Tested Review Screen

### ISSUE THREAD

**Issue by QISPSK** [EyeSeeTea/SurveillanceCambodiaApp#113]
Is it possible to add a review screen for “Negative” and “Not Tested” responses as well?

**Comment by ifoche** [comment]
Sure, and wouldn't take too much time

**Comment by QISPSK** [comment]
@ifoche Can you change the colors for when the provider selects "Not Tested" and "RDT Stock Out?" They are currently the same color

**Comment by ifoche** [comment]
Sure, sorry for that
