### ISSUE TITLE
Case Classification - Review Screen

### ISSUE THREAD

**Issue by QISPSK** [EyeSeeTea/SurveillanceCambodiaApp#116]
![image](https://cloud.githubusercontent.com/assets/17549893/25211876/ac7c236c-25b1-11e7-8222-20aa0077a8c1.png)

Is it possible to change “Yes/No” response for patient history to “Imported/Local”?

In Khmer, these would be:
1.	Imported: ករណីនាំចូល
2.	Local: ករណីក្នុងតំបន់

**Comment by ifoche** [comment]
It's possible, but it's not so quick at it would be if it were just a translation problem. The problem here is that Yes/No is also used by other questions, so we cannot just translate. We need a new optionSet DHIS2 side, and change CSVs app side to consequently match those codes.

**Comment by rbeccapotter** [comment]
@QISPSK I recommend leaving this as is for a different reason. As I've mentioned before, a malaria case that traveled to another village is not an imported case. What you are capturing is data about risk factors relating to travel. I would not support perpetuating the misnomer of "imported case" based on extremely limited travel history data and zero case investigation protocol. Just my two cents...

**Comment by QISPSK** [comment]
@rbeccapotter For some reason your comment isn't showing up on my end, but I agree about drawing the distinction between "Imported/Local" from a full case investigation and this question. I do still feel that "Yes/No" is far too general, however, for providers skimming a review slide. Perhaps we could change the text to "Slept Outside of Village/Slept in Village?"

**Comment by rbeccapotter** [comment]
@QISPSK I misunderstood your issue :) You can do whatever makes sense so that providers know what they are "reviewing".

**Comment by QISPSK** [comment]
@ifoche Can you further explain why we can't simply just translate Option_Text_Test_Classification_Yes/No on POEditor? Making the changes on the DHIS2 side would be nice, but those viewing the data understand that a "yes" indicates that the patient slept outside of the village within the past two weeks. The review screen would only be seen by the provider and we worry that a simply "Yes/No" on the review screen isn't enough for the provider when reviewing before submitting a survey.

**Comment by ifoche** [comment]
@QISPSK sorry, I thought you wanted not only to change it in the review screen but it to be sent like that to DHIS2 and be able to see that value server side when analysing data. If it's only a matter of showing it in the review screen, you can just translate as you said in POEditor. 

Just to provide an alternative too (just in case), for Save the Children Myanmar App we implemented a solution that consisted on showing a short title before the option and that short title was also available in POEditor. Including that is also (not so quick as POEditor edition but not more than 5 hours).

**Comment by QISPSK** [comment]
@ifoche I'm not sure what you mean regarding the Save the Children app, could you attach a picture/example, perhaps? 

Regardless, I've gone ahead and updated both the English and the Khmer text on POEditor to say "Slept in the Village" and "Slept Outside of the Village".

**Comment by ifoche** [comment]
Hi @QISPSK,

Save the Children App is a derivated from PSI MCS app that implements several modifications, but still have some common concepts. For instance, the review screen is similar, but they have multiple yes/no questions, so they needed to identify them clearly on the review screen. That's why we implemented titles for them in the review screen. Please look at the following screenshot
![review_screen](https://cloud.githubusercontent.com/assets/10931645/25541456/02296632-2c4f-11e7-8878-b028d2dc98a9.png)

However, I interpret from your comment that we proceed with the POEditor import and leave any solution like this for the future, right? Thanks!

**Comment by QISPSK** [comment]
@ifoche Interesting. That is correct, we can proceed with the POEditor edits and go from there. If we feel like it's a major need in the future, we can consider this alternative.
