### ISSUE TITLE
Incorrect Translations - Sent Screen/Monitor Module

### ISSUE THREAD

**Issue by QISPSK** [EyeSeeTea/SurveillanceCambodiaApp#118]
![image](https://cloud.githubusercontent.com/assets/17549893/25211953/17519852-25b2-11e7-9b37-dbcc627da6fd.png)

Incorrect Translations:
1.	Last 6 Days
a.	៦ ថ្ងៃចុងក្រោយ
2.	Last 6 Weeks
a.	៦ សប្ដាហ៍ចុងក្រោយ
3.	Last 6 Months
a.	៦ ខែចុងក្រោយ
4.	Last Week
a.	សប្តាហ៍ចុងក្រោយ
5.	Last Month
a.	ខែចុងក្រោយ

These items also need to be updated in the monitor module to ensure consistency. If needed, we can use a different phrase to indicate past time periods (i.e., ៦ ខែមុន) if ចុងក្រោយ doesn’t fit in the popup window

**Comment by ifoche** [comment]
I think you can do it in POEditor by [searching  for last](https://poeditor.com/projects/po_edit?order=&filter=&id=50144&id_language=27&search=last). After the modification, we can easily include it in next build.

**Comment by QISPSK** [comment]
Updated on POEditor

**Comment by ifoche** [comment]
Thanks! we will incorporate it into next release

**Comment by QISPSK** [comment]
@ifoche Updated these in POEditor to highlight the difference between "Last" and "Latest" in Khmer.
