### ISSUE TITLE
Question 5: Graphic design - Text

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#12]
Feedback from qispsk@gmail.com : The translation here seems not the same to the translation we did on Gdrive. 

 [Link to buddybuild feedback from build 7](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=56dd35549f12090100d5aaa9&bnum=7)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/56dcafa10b8e3e0100d226ce/8794bec1-0006-4ca0-8c42-61028f4d43b9.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>7</td></tr><tr><td>Device type</td><td>LG-H324</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 786px</td></tr><tr><td>Battery</td><td>34% Unplugged</td></tr><tr><td>Memory free</td><td>156 MB / 711 MB</td></tr></table>

**Comment by adrianq** [comment]
@QISPSK  The texts are part of the images. We are using the old ones as we haven't received the new artwork. Once we receive it we will update the code and release again. Closing this card as it is not actually a bug...

**Comment by gtrsmith** [comment]
I am reopening and assigning this to me. I will work with graphic designer to address.
