### ISSUE TITLE
Hardcoding data.psi-mis.org URL for v1.3

### ISSUE THREAD

**Issue by QISPSK** [EyeSeeTea/SurveillanceCambodiaApp#122]
Is there any way we can hard code in the URL? It sounds like a few providers have accidentally clicked on this feature and changed the URL which has prevented them from sending data. It would be nice if we could keep the URL locked in for now and potentially open it back up in the future if we need to use multiple URLs in the future (i.e., if/when the government switches to DHIS2 and they want data sent directly to their servers).

**Comment by ifoche** [comment]
@QISPSK what about hiding the URL and only show it when "developers options" is activated? Would that work? Otherwise, we would be blocking the app to a concrete URL and forcing the users whenever they have that need, to install a new version of the app.

**Comment by QISPSK** [comment]
@ifoche I think hiding it behind developer options would work fine for now and we can monitor it to see if anyone changes it accidentally going forward.
