### ISSUE TITLE
Khmer Days on the Monitor Module

### ISSUE THREAD

**Issue by QISPSK** [EyeSeeTea/SurveillanceCambodiaApp#123]
![screenshot_2017-05-08-10-13-09](https://cloud.githubusercontent.com/assets/17549893/25788961/3f7de5e6-33d7-11e7-8c29-e994af6cfecc.png)

Not sure why this changed, but it looks like the formatting of the day in the header of the monitor module when "latest 6 days" is selected is off. Is this something we can fix in POEditor?

**Comment by ifoche** [comment]
@QISPSK are you referring to the fact that day 5 in your screenshot is taking more space than the others and so the whole title fits in 1 line while the others take 2 lines? If that's the case, that behavior comes from the fact that 100% is larger than 0%, and the column is adapting its size to that. Maybe we can use a fix column size, but then you may start having a little scroll in some screens where you didn't before... Do you want us to do that?

**Comment by QISPSK** [comment]
@ifoche Ah good catch! I didn't realize that this was from the 100% at the bottom. I'd say we can safely ignore this issue and address this in v1.4 when we come up with a different solution for the monitor module.
