### ISSUE TITLE
Header: Khmer language

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#14]
Feedback from clussiana@psi.org : Wondering if PSK wants the headers of this landing page in Khmer...

 [Link to buddybuild feedback from build 7](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=56dd9d736d745e01004ff263&bnum=7)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/56dcafa10b8e3e0100d226ce/9a9d61d8-6661-460a-994a-698b7618b567.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>7</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>100% Unplugged</td></tr><tr><td>Memory free</td><td>403 MB / 1376 MB</td></tr></table>

**Comment by cristinaelle** [comment]
@QISPSK : please, have a look at this comment of mine.

**Comment by adrianq** [comment]
@cristinaelle These headers depend on the device preferences. We currently support English, Spanish, France and Khmer. The only strings are not translated are the ones in the Dhis2 database (questions and answers for instances) because of Dhis2 api limitation. If @QISPSK  has Khmer as the default device language he should see everything in Khmer...

**Comment by gtrsmith** [comment]
I am closing this ticket because Adrian resolved with his explanation.
