### ISSUE TITLE
Landing page: Survey display

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#18]
Feedback from clussiana@psi.org : For some reason, sometimes I have empty surveys in the completed ones. They appear together with actual surveys.

 [Link to buddybuild feedback from build 8](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=56ddad347decba01000f888f&bnum=8)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/56dd9e12d153200100adab26/ed9f6384-2a3e-41f0-8cc6-c5aaf74ae740.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>8</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>100% Unplugged</td></tr><tr><td>Memory free</td><td>297 MB / 1376 MB</td></tr></table>

**Comment by adrianq** [comment]
@cristinaelle  Can you try to find when and how it happens? I haven't seen this bug before and unless you provide a little bit of context it is going to be really difficult to catch it. Can you please try to find a pattern?

**Comment by cristinaelle** [comment]
mh, let me try. I've resent 3 positives, 3 negatives and 3 not tested and nothing has happened so far. I've closed the app and opened it again, resent 3 each, and it has not happened again.
I've clicked on those 2 "empty" surveys to see if I was able to go ahead with the survey, in case those are uncompleted surveys. I can't: it opens the first question (+/-/x) but then I can't click on any of the 3 questions.

**Comment by gtrsmith** [comment]
Hi Cristina, 

The 'empty' surveys are resulting from answering either '-' or 'x' to the first question. If you answer either of those responses, the survey ends. It is done this way intentionally. The goal is only to collect information on + individuals.

**Comment by adrianq** [comment]
@gtrsmith I think you have misunderstood the issue. If you look at @cristinaelle screenshot there are two surveys at the top that don't have any answer in the RDT column. This is definitively an error but I haven't been able to reproduce it so far. I am keeping an eye on it in order to understand when it happens... Please let me know if it happen to you.

**Comment by cristinaelle** [comment]
Yep, Adrian, you're right.
