### ISSUE TITLE
Question 5: Graphic Design - Artwork

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#19]
Feedback from qispsk@gmail.com : Artwork includes .pdf comment box, should be removed.

 [Link to buddybuild feedback from build 8](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=56deadbefabbdf01004b2563&bnum=8)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/56dd9e12d153200100adab26/8cb16761-1ca7-497d-8d92-0ac6bec04910.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>8</td></tr><tr><td>Device type</td><td>LG-H324</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 786px</td></tr><tr><td>Battery</td><td>100% Unplugged</td></tr><tr><td>Memory free</td><td>209 MB / 711 MB</td></tr></table>

**Comment by adrianq** [comment]
@QISPSK  We are still waiting for the new artwork and, in particularly, for two of the treatment options. As we wanted to release a version for you to test it I took the pictures from the pdf. Once the new artwork is ready and delivered, we will replace those images with the new ones.

**Comment by gtrsmith** [comment]
I am meeting with graphic designer this afternoon and will have final artwork soon
