### ISSUE TITLE
Landing Page: Push feature

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#20]
Feedback from clussiana@psi.org : Should we remove the option of pushing surveys by holding the finger on a survey row among Pending send? Thus might create confusion to providers.

 [Link to buddybuild feedback from build 8](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=56e68ebc5544640100b394e1&bnum=8)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/56dd9e12d153200100adab26/c3b1e033-d58d-41dd-bbc1-8a0d83791791.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>8</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>51% Unplugged</td></tr><tr><td>Memory free</td><td>314 MB / 1376 MB</td></tr></table>

**Comment by adrianq** [comment]
@cristinaelle Sure, we can do it. It is just about commenting out a few line. TBH, I have already thought about removing it @gtrsmith @rodmelia  just to confirm this is not needed... do you agree  about removing this feature?

**Comment by gtrsmith** [comment]
@adrianq I agree with this.
