### ISSUE TITLE
Review feature: limit review for negative or not tested

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#21]
Feedback from clussiana@psi.org : I'm reviewing a survey that I sent and this is a negative  test. In the review I can see all the quesrions, even the ones I have not answered. Can we modify this so that neg and not tested cases don't show all the questions, but just the first one?

 [Link to buddybuild feedback from build 11](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=56e8def79492a3010040a805&bnum=11)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/56e8c3568418ae01009093f9/1476bb18-38df-4900-b056-dbfba7f7d869.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>11</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>80% Unplugged</td></tr><tr><td>Memory free</td><td>363 MB / 1376 MB</td></tr></table>

**Comment by gtrsmith** [comment]
This does not have to be done in time for this field test but it is a good idea. @adrianq, lets discuss how complex this is.

**Comment by gtrsmith** [comment]
Please aim to address this for 4.1
