### ISSUE TITLE
Landing Page: Provider name in header

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#22]
Feedback from clussiana@psi.org : Please, include the name of the proivider at the top, as it appears in the actual survey.

 [Link to buddybuild feedback from build 11](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=56e8df5d28bc530100782b7e&bnum=11)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/56e8c3568418ae01009093f9/d7139fca-5afd-4261-9a45-57a95515ccaf.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>11</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>80% Unplugged</td></tr><tr><td>Memory free</td><td>348 MB / 1376 MB</td></tr></table>

**Comment by gtrsmith** [comment]
Yes, this should be in the header if it is an easy change to implement.
