### ISSUE TITLE
Landing Page: Font size of Send survey and Pending survey.

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#23]
Feedback from clussiana@psi.org : Increase font size of Send survey and Pending survey.

 [Link to buddybuild feedback from build 11](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=56e8e00c85e23601008b4ef9&bnum=11)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/56e8c3568418ae01009093f9/916e3ec6-9d48-4677-8836-832aeeeef4dc.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>11</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>79% Unplugged</td></tr><tr><td>Memory free</td><td>321 MB / 1376 MB</td></tr></table>

**Comment by adrianq** [comment]
@cristinaelle  We are having some problems depending on the device and the language with the look and feel of the dashboard. In Khmer with a small screen it doesn't look as nice as it looks in your device/emulator. I think the best approach is going to be probably to revert the changes or something in between the new and the former one.

**Comment by gtrsmith** [comment]
@adrianq lets discuss on our call

**Comment by gtrsmith** [comment]
We will wait for field test to determine if font size needs to change.
