### ISSUE TITLE
Monitor: include provider name

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#25]
Feedback from clussiana@psi.org : Monitor module: include the name of the proivder. at the top.

 [Link to buddybuild feedback from build 11](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=56e8e16928bc530100782b87&bnum=11)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/56e8c3568418ae01009093f9/ba57fbdc-8a15-4a93-b721-9fe656abd8f6.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>11</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>77% Unplugged</td></tr><tr><td>Memory free</td><td>311 MB / 1376 MB</td></tr></table>

**Comment by gtrsmith** [comment]
@adrianq how complex is this? Lets discuss.
