### ISSUE TITLE
Monitor: Graphic Design

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#26]
Feedback from clussiana@psi.org : Will the graphic designer review the Monitor tables, too? 

 [Link to buddybuild feedback from build 11](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=56e8e1a285e23601008b4efe&bnum=11)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/56e8c3568418ae01009093f9/a16ab51f-16dc-4d14-a4e7-8cb28cd165ce.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>11</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>77% Unplugged</td></tr><tr><td>Memory free</td><td>310 MB / 1376 MB</td></tr></table>

**Comment by cristinaelle** [comment]
@gtrsmith

**Comment by gtrsmith** [comment]
No plans to at the moment.
