### ISSUE TITLE
Monitor: layout

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#27]
Feedback from qispsk@gmail.com : Column size is inconsistent in Khmer

 [Link to buddybuild feedback from build 11](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=56e918366a87a20100002749&bnum=11)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/56e8c3568418ae01009093f9/e04703b7-4e99-431d-bd43-a93aefcd2b7b.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>11</td></tr><tr><td>Device type</td><td>LG-H324</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 786px</td></tr><tr><td>Battery</td><td>25% Unplugged</td></tr><tr><td>Memory free</td><td>162 MB / 711 MB</td></tr></table>

**Comment by adrianq** [comment]
@QISPSK  I am not sure if I fully understand the problem. Do you want all the columns to be of the same size? Do you want the two tables to look the same? Keep in mind there is not too much we can do if the device screen is not big enough

**Comment by gtrsmith** [comment]
@adrianq lets discuss - this is a low priority but I see what the team means.

**Comment by QISPSK** [comment]
@adrianq 
It is definitely a minor issue, but if we could keep the column sizes consistent it would visually make things more clear.
