### ISSUE TITLE
Landing Page: Font Size

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#29]
Feedback from qispsk@gmail.com : Font size increase on the first page makes it difficult to see sent and unsent surveys on the phones that the providers will be using

 [Link to buddybuild feedback from build 11](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=56e91a409492a3010040a89e&bnum=11)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/56e8c3568418ae01009093f9/6b42b9c6-246f-4d1a-809c-c9cdf50db822.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>11</td></tr><tr><td>Device type</td><td>LG-H324</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 786px</td></tr><tr><td>Battery</td><td>10% Unplugged</td></tr><tr><td>Memory free</td><td>162 MB / 711 MB</td></tr></table>

**Comment by adrianq** [comment]
@QISPSK I will revert that change and keep it with the original font size.

**Comment by gtrsmith** [comment]
I agree with decision to revert back
