### ISSUE TITLE
Question 3: Keypad display

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#3]
Feedback from clussiana@psi.org : Is it possible to show the key pad with numbers automatically? At the moment has to click in the space for the key pad to show up.

 [Link to buddybuild feedback from build 7](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=56dd02b0c225260100c5914d&bnum=7)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/56dcafa10b8e3e0100d226ce/7b36e12d-59a5-4138-806a-f103ba846242.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>7</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>100% Full</td></tr><tr><td>Memory free</td><td>240 MB / 1376 MB</td></tr></table>

**Comment by gtrsmith** [comment]
@adrianq If this is easy, please implement. If it is complex, let me know and we can discuss if this is a priority.
