### ISSUE TITLE
Review feature: review screen, basic

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#32]
KH team to submit review page. Initial draft [here](https://drive.google.com/open?id=0BwFVG9gNmqDyclFQY3diSVpCQkE)

Review page will display after the phone number question. Review page will display a table with Khmer question and the answer provided in the tablet. Below the table, there will be a 'cancel' or 'submit' button. 

Code for functionality can be built as we wait for review page.

**Comment by gtrsmith** [comment]
Question for KH team - is this review page final? Does it need additional graphic design work?
