### ISSUE TITLE
Bug: N/A data - positive RDT test with no data

### ISSUE THREAD

**Issue by gtrsmith** [EyeSeeTea/SurveillanceCambodiaApp#33]
Theoretically, if the RDT test is positive (question 1), the user should be forced to fill out the remainder of the survey. They should not be able to skip fields. The DHIS analytics, however, show many cases where a positive case is registered and resulting data fields are missing. See image below. 

The only question that should remain optional is the phone number question. Users should be able to leave this blank and still submit a survey.

![n a data - positive rdt w no data](https://cloud.githubusercontent.com/assets/14224713/14652607/4449f034-0632-11e6-948a-957acca26d17.PNG)

**Comment by rodmelia** [comment]
Graham will upload video showing possible cause for the problem.

**Comment by gtrsmith** [comment]
Video which may explain issue is here: https://drive.google.com/a/psi.org/file/d/0BwQE0UgKE3AmV0lSQlJwU3EteDA/view

As you can see, user is able to select multiple answers on first question which causes the application to skip several questions.

**Comment by adrianq** [comment]
@gtrsmith @rodmelia Now when you select an image you won't be able to select any other answer during the transition time (the time when the answer is highlight and the other are darken).
