### ISSUE TITLE
Bug: N/A data - blank assessments

### ISSUE THREAD

**Issue by gtrsmith** [EyeSeeTea/SurveillanceCambodiaApp#35]
DHIS shows a number of blank assessments sent from phones. The app should not be able to send a blank assessment and we need to determine why this is happening. See image below. 

![n a data - blank assessments](https://cloud.githubusercontent.com/assets/14224713/14652714/c1d8c3cc-0632-11e6-8e46-c10446a16848.PNG)

**Comment by adrianq** [comment]
@gtrsmith have you seen this behaviour again? Do you think we can close this card?
