### ISSUE TITLE
Monitor: Change days to dates

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#39]
Change the days to dates, as in '11th', '12th', '13th', '31st', '1st' etc

KH team provided Khmer text for 'th', 'st', 'rd', and 'nd' here: https://docs.google.com/spreadsheets/d/1i1Lj-0y-kjUQBC6UFmHLDA6RRvZpmADCaPZnoMXFjwk/edit#gid=1103624326. 

 [Link to buddybuild feedback from build 11](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=57168a901ec52f0100740833&bnum=11)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/56e8c3568418ae01009093f9/17a42e41-3d32-4ff8-b180-9515fd05119b.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>11</td></tr><tr><td>Device type</td><td>A0001</td></tr><tr><td>Screen size</td><td>1080</td></tr><tr><td>Screen size</td><td>1080px by 1920px</td></tr><tr><td>Battery</td><td>73% Unplugged</td></tr><tr><td>Memory free</td><td>1108 MB / 2877 MB</td></tr></table>

**Comment by rodmelia** [comment]
We just found out that all you need to do is to add the prefix "ទីី" to the date of the month:

ទីី01
ទីី02
...
ទីី31

**Comment by gtrsmith** [comment]
they have also included text for the months in a similar fashion. So the months look like:

ខែ01
ខែ02
ខែ03
