### ISSUE TITLE
Question 3: Layout

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#4]
Feedback from clussiana@psi.org : The space for the age is very small compared to how much space is available here. Can we make this much much bigger and fancier? We won't have more than 2 digits, so we need a tall and narrow rectangulaar box rather than a short and long one.

 [Link to buddybuild feedback from build 7](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=56dd0367c225260100c59152&bnum=7)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/56dcafa10b8e3e0100d226ce/61fa859d-5434-4c03-85d6-821a62ac0622.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>7</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>100% Full</td></tr><tr><td>Memory free</td><td>201 MB / 1376 MB</td></tr></table>

**Comment by gtrsmith** [comment]
Adrian, do what you can but dont spend too much time on this. It is low priority.
