### ISSUE TITLE
Question 7: Hard code phone number format

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#43]
Hardcode phone number format to the following:

0XX XXX XXXX

 [Link to buddybuild feedback from build 11](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=57168cf40d0bb20100bc7df6&bnum=11)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/56e8c3568418ae01009093f9/38a3df85-ab16-403c-9769-d76128b8f733.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>11</td></tr><tr><td>Device type</td><td>A0001</td></tr><tr><td>Screen size</td><td>1080</td></tr><tr><td>Screen size</td><td>1080px by 1920px</td></tr><tr><td>Battery</td><td>71% Unplugged</td></tr><tr><td>Memory free</td><td>1067 MB / 2877 MB</td></tr></table>

**Comment by gtrsmith** [comment]
The phone number format is not hard coded – we just have the 0XX XXX XXXX in the data entry field now, which we have to delete and then enter a proper phone number. Perhaps this ticket was not clear – let me know if we should discuss tomorrow. Rodolfo can also help explain. We need the phone number to be either nothing or follow the 0XX XXX XXXX format in order for the survey to be submitted –that is what we were looking for.

**Comment by adrianq** [comment]
Moving this card to Done. If by any chance what we have at the moment is not what you were expecting let us know...
