### ISSUE TITLE
Question 3: Increase size of button

### ISSUE THREAD

**Issue by gtrsmith** [EyeSeeTea/SurveillanceCambodiaApp#45]
KH has submitted imagery:

![khmer ok button screenshot](https://cloud.githubusercontent.com/assets/14224713/14675119/a1e9e02c-06c4-11e6-9647-3c12a710de93.png)

**Comment by rodmelia** [comment]
increase width ob the button so whole word can fit (it shouldn't go into next line)

**Comment by adrianq** [comment]
@QISPSK  I have increased the size of the button but please let me know if you still have problem about the visualization. It is a little bit difficult to reproduce the problem.
