### ISSUE TITLE
clussiana@psi.org on build #12: This is how it appears when I have to write a phone number.…

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#50]
Feedback from clussiana@psi.org : This is how it appears when I have to write a phone number. I have to delete the Xs and type numbers.

 [Link to buddybuild feedback from build 12](https://api.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=571f32a81d834601002eff6f&bnum=12)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/571ecd8a4571aa0100339d18/9a05dafd-f7a0-4b16-be85-e4b03a5e5042.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>12</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>46% Unplugged</td></tr><tr><td>Memory free</td><td>339 MB / 1376 MB</td></tr></table>

**Comment by gtrsmith** [comment]
This is issue 43 - I updated that ticket and moved it back to ready - so I am closing this one out.
