### ISSUE TITLE
clussiana@psi.org on build #12: I guess it's not sending the survey because I have not…

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#51]
Feedback from clussiana@psi.org : I guess it's not sending the survey because I have not selected any OU?? Now it's been some time since I've completed the survey ansd it's not sent yet.

 [Link to buddybuild feedback from build 12](https://api.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=571f3434fe6fcc0100432abe&bnum=12)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/571ecd8a4571aa0100339d18/71b703b9-9929-49ef-b868-dd7d263a83f8.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>12</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>44% Unplugged</td></tr><tr><td>Memory free</td><td>247 MB / 1376 MB</td></tr></table>

**Comment by gtrsmith** [comment]
If you havent selected the OU and logged into the app, the survey will just sit there - can you confirm this is the case? It is not a bug if so - this is how it is designed to function

**Comment by adrianq** [comment]
Yes, this is done on purpose. We would like anybody to 'play' with the app but only if you have a dhis2 server account you can send surveys (because you need to log-in in order to select a OU). Closing this card as it is not a bug...
