### ISSUE TITLE
Title: Introduce Khmer

### ISSUE THREAD

**Issue by gtrsmith** [EyeSeeTea/SurveillanceCambodiaApp#52]
Please add Khmer language to application title. 

Waiting on KH to provide translation

**Comment by QISPSK** [comment]
Application still appears as "Malaria Case Surveillance" when OS language is changed to Khmer.

**Comment by ifoche** [comment]
That's strange, we've even seen reports from your side with the application title in khmer. We're still talking about the application title and not the application name, isn't it?

**Comment by ifoche** [comment]
@QISPSK This issue talks about the title, not the name of the app. Can you please tell me whether that may be the confusion? Are you talking about the name while what we've done is changing the title?

**Comment by QISPSK** [comment]
I think that is the confusion. Appreciate you changing the name in the app though! Is it possible to change the name of the app to Khmer when the phone is in Khmer? If not, no worries, or if the issue is too complex to get pushed out in the next day or so, we can always move it to S6.
