### ISSUE TITLE
qispsk@gmail.com on build #25: The reason for not tested should appear after this…

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#54]
Feedback from qispsk@gmail.com : The reason for not tested should appear after this selection. It should not appear after negative!

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/57586bc3bf09ff010013bc3a/3286958f-8a2a-4e9e-9019-c906df024f6a.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>25</td></tr><tr><td>Device type</td><td>LG-H324</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 786px</td></tr><tr><td>Battery</td><td>83% Unplugged</td></tr><tr><td>Memory free</td><td>145 MB / 711 MB</td></tr></table>

 [Link to buddybuild feedback from build 25](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=5758fd791b89120100a3a435&bnum=25)

**Comment by ifoche** [comment]
you're right. Working on it
