### ISSUE TITLE
qispsk@gmail.com on build #25: As Eli mentioned this should change the translation in Khmer…

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#55]
Feedback from qispsk@gmail.com : As Eli mentioned this should change the translation in Khmer for DHA-PIP for the monitor module

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/57586bc3bf09ff010013bc3a/f5b91ad3-69b1-4dec-af5d-473376ae1b80.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>25</td></tr><tr><td>Device type</td><td>LG-H324</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 786px</td></tr><tr><td>Battery</td><td>81% Unplugged</td></tr><tr><td>Memory free</td><td>148 MB / 711 MB</td></tr></table>

 [Link to buddybuild feedback from build 25](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=5758feab3a904201000bc3bf&bnum=25)

**Comment by ifoche** [comment]
got it. Working on it
