### ISSUE TITLE
qispsk@gmail.com on build #25: The keyboard pop up on Species screen after the age entered…

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#57]
Feedback from qispsk@gmail.com : The keyboard pop up on Species screen after the age entered which cause species screen smaller and difficult to read.

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/57586bc3bf09ff010013bc3a/582e2e77-a1a8-4935-bcdc-437a0c15f167.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>25</td></tr><tr><td>Device type</td><td>LG-H324</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 786px</td></tr><tr><td>Battery</td><td>57% Unplugged</td></tr><tr><td>Memory free</td><td>149 MB / 711 MB</td></tr></table>

 [Link to buddybuild feedback from build 25](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=57591cc14d6deb01001b6aa1&bnum=25)

**Comment by ifoche** [comment]
@QISPSK if you press back the keyboard hides and then you see the options big again. The request is to by default hide the keyboard on moving to the following question?

**Comment by QISPSK** [comment]
@ifoche That is correct. After the age entry screen, the keyboard should hide by default as there is no need to use the keyboard on the Species screen.
