### ISSUE TITLE
qispsk@gmail.com on build #25: Sent Unsent and Monitoring need to be translated into Khmer.

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#58]
Feedback from qispsk@gmail.com : Sent Unsent and Monitoring need to be translated into Khmer.

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/57586bc3bf09ff010013bc3a/39199595-c45e-4500-aca6-5ff0a63e55bc.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>25</td></tr><tr><td>Device type</td><td>LG-H324</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 786px</td></tr><tr><td>Battery</td><td>55% Unplugged</td></tr><tr><td>Memory free</td><td>151 MB / 711 MB</td></tr></table>

 [Link to buddybuild feedback from build 25](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=57591d934d6deb01001b6aa7&bnum=25)

**Comment by ifoche** [comment]
Sorry for that. Working on it
