### ISSUE TITLE
Question 5: Artwork order

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#6]
Feedback from clussiana@psi.org : For Sophia to change the order of these images: first the 4 DHA-PIP treatments and then the AS/MQ and then the referral.

 [Link to buddybuild feedback from build 7](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=56dd042fc225260100c59153&bnum=7)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/56dcafa10b8e3e0100d226ce/ec811bc0-fac2-4a8f-a97f-741d03ff09a2.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>7</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>100% Full</td></tr><tr><td>Memory free</td><td>300 MB / 1376 MB</td></tr></table>

**Comment by adrianq** [comment]
@cristinaelle Actually we can define the order of the images (they are 6 individual images). TBH I haven't paid too much attention to this  as we were waiting for the new artwork. Once we have it I will update the image and reorder it according to what you have just said.

**Comment by cristinaelle** [comment]
ok, so we can close this for the moment, I guess. thanks!

**Comment by gtrsmith** [comment]
I will work with Sophie on this today
