### ISSUE TITLE
clussiana@psi.org on build #25: In case of Not tested, why the answer to the next question…

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#60]
Feedback from clussiana@psi.org : In case of Not tested, why the answer to the next question doesn't show up in the Info column? 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/57586bc3bf09ff010013bc3a/6631bfd1-a45d-4a1f-8b38-0da51f50ddc6.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>25</td></tr></table>

 [Link to buddybuild feedback from build 25](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=5759273032322f010011baaf&bnum=25)

**Comment by ifoche** [comment]
You're right, we have to include that into the info column. Working on it

**Comment by cristinaelle** [comment]
Great. Please, note that as Eli already reported, at the moment that question (In case of Not tested, why? Danger signs, Stock-out of RDTs, etc) is assigned to the wrong answer of the previous question (at the moment it's assigned at Negative while it should be assigned to Not tested).

**Comment by ifoche** [comment]
@cristinaelle yes, thanks, we've already addressed that issue. We're reviewing the whole info column, because we were not taking into account the new answers in that column. By tomorrow (the French tomorrow) we expect to release the solution for all the bugs that are at this moment reported
