### ISSUE TITLE
clussiana@psi.org on build #25: In the Sent tab, do you think it's possible to change the…

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#65]
Feedback from clussiana@psi.org : In the Sent tab, do you think it's possible to change the denominator shown at the bottom left corner from 9 to 2 in case of Not tested and from 9 to 1 in case of Negative?

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/57586bc3bf09ff010013bc3a/6e1ff669-b2f0-4231-9238-675519d867e1.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>25</td></tr></table>

 [Link to buddybuild feedback from build 25](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=575a74ac4f163101004279d5&bnum=25)

**Comment by rodmelia** [comment]
This was not in the specs for S5. We think that there is a solution, but will increase the number of hours.

**Comment by rodmelia** [comment]
@ifoche - please only do if it takes less than 5 hours
