### ISSUE TITLE
qispsk@gmail.com on build #25: Can we hide "Send" "Unsent" and "Monitor" option when thr…

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#66]
Feedback from qispsk@gmail.com : Can we hide "Send" "Unsent" and "Monitor" option when thr provider is taking a survey?

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/57586bc3bf09ff010013bc3a/9e72acd1-3643-4ff4-94e2-629f7f7940aa.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>25</td></tr><tr><td>Device type</td><td>LG-H324</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 786px</td></tr><tr><td>Battery</td><td>13% Unplugged</td></tr><tr><td>Memory free</td><td>128 MB / 711 MB</td></tr></table>

 [Link to buddybuild feedback from build 25](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=575a7a204f16310100427a0e&bnum=25)

**Comment by rodmelia** [comment]
Was not in the S5 specs. It will be attempted, but if there is a risk of introducing new crash, then it will be moved to S6.
