### ISSUE TITLE
clussiana@psi.org on build #26: When I review a sent survey and then go back, it takes me…

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#68]
Feedback from clussiana@psi.org : When I review a sent survey and then go back, it takes me back to the Unsent tab. Shouldn't it take me back to the Sent tab?

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/575b4c1dbb15b50100c043ee/7ef01c86-c2de-4672-8015-e6e2ad019d46.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>26</td></tr></table>

 [Link to buddybuild feedback from build 26](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=575c453c46cc3e0100eb93fa&bnum=26)

**Comment by ifoche** [comment]
It's reasonable to do that, yes.
