### ISSUE TITLE
clussiana@psi.org on build #26: In the Sent tab, for Not tested ones, is it possible to…

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#69]
Feedback from clussiana@psi.org : In the Sent tab, for Not tested ones, is it possible to change the denominator at the bottom left corner from 1 to 2, please?

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/575b4c1dbb15b50100c043ee/9106c55d-5f18-4f13-a28b-7216efb92da4.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>26</td></tr></table>

 [Link to buddybuild feedback from build 26](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=575c4c3375cea401003ea789&bnum=26)

**Comment by ifoche** [comment]
@cristinaelle , you're right. We have a bug on the denominator when reviewing the questions. We didn't check that. It's the same on #70 and this will happen for all the questions in read-only mode.
