### ISSUE TITLE
Question 7: Layout

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#7]
Feedback from clussiana@psi.org : Reorganize the space. We have 10 digits maximum. Let's make this box more narrow and tall, rather than short and long.

 [Link to buddybuild feedback from build 7](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=56dd0477c49f9f010026fb2e&bnum=7)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/56dcafa10b8e3e0100d226ce/ba8050d4-4135-4644-bf94-a857c719c3d5.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>7</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>100% Full</td></tr><tr><td>Memory free</td><td>307 MB / 1376 MB</td></tr></table>

**Comment by gtrsmith** [comment]
Adrian, do what you can but dont spend too much time here. This is a low priority issue
