### ISSUE TITLE
Add space between RDT and Khmer Scripts

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#71]
Feedback from qispsk@gmail.com : Should have a space between RDT and Khmer Scripts.

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/575b4c1dbb15b50100c043ee/dad9e7ce-13f4-4e96-a872-d438fcba0d22.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>26</td></tr><tr><td>Device type</td><td>LG-H324</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 786px</td></tr><tr><td>Battery</td><td>100% Unplugged</td></tr><tr><td>Memory free</td><td>189 MB / 711 MB</td></tr></table>

 [Link to buddybuild feedback from build 26](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=575c9585d5130001004b72db&bnum=26)

**Comment by ifoche** [comment]
Please find attached in this issue the image that you sent us in svg. Like in ACT, could you provide us with a definitive image, the space included? Thanks

![rdt_space_bug](https://cloud.githubusercontent.com/assets/10931645/16000305/e9c870d2-314b-11e6-93be-4d0480644053.png)
