### ISSUE TITLE
Add a space to break between ACT and…

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#73]
Feedback from qispsk@gmail.com : Again here should have a space to break between ACT and Khmer Scripts

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/575b4c1dbb15b50100c043ee/de33cce9-6eec-4733-9572-4cc94449d0fc.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>26</td></tr><tr><td>Device type</td><td>LG-H324</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 786px</td></tr><tr><td>Battery</td><td>98% Unplugged</td></tr><tr><td>Memory free</td><td>168 MB / 711 MB</td></tr></table>

 [Link to buddybuild feedback from build 26](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=575c96e7d5130001004b72e1&bnum=26)

**Comment by ifoche** [comment]
I'm attaching to this issue the image as we got from you in the svg files. I cannot see the space there. Could you provide us with an image with the space? Thanks

![act_no_space_bug](https://cloud.githubusercontent.com/assets/10931645/16000130/95b5c54a-314a-11e6-923f-241e3e6d25e1.png)
