### ISSUE TITLE
clussiana@psi.org on build #27: Positivity rate is: sum of Pos/(sum of Pos and Neg). 
I…

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#76]
Feedback from clussiana@psi.org : Positivity rate is: sum of Pos/(sum of Pos and Neg). 
I think I double checked this in a previous version and it was working fine. Now it seems that Not tested cases have been included in the den. Please, refer to the file below.

https://docs.google.com/spreadsheets/d/1CQgZ1EKrVmtSzbR5C_4GH0FplvAwtTgAzFL8-sOK_3U/edit#gid=927663048

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/575f6a3cfb328301003fe0cc/f3ce95e0-5612-4cac-991d-b768d10880df.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>27</td></tr></table>

 [Link to buddybuild feedback from build 27](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=575f979635a54301003a74a6&bnum=27)

**Comment by ifoche** [comment]
@cristinaelle in the screenshot of this issue I can see Positivity rate: 35% for 12 positives in 34 suspected cases...Please correct me if I'm wrong but 12 positives in 34 suspected cases means a positivity rate of 35%...and it's the same for the rest. I don't see the error. It's exactly the same as in the file you shared, Positivity rate = (Positives / Suspected cases) x 100.

**Comment by rodmelia** [comment]
@cristinaelle - I agree with Ignacio - 12/34 = 35%

**Comment by rodmelia** [comment]
OK - the correct formula is Pos/(Pos+Neg)
