### ISSUE TITLE
Statistics: Placement of monitoring statistics

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#8]
Feedback from clussiana@psi.org : Nice to see this! 
For RM: what if we put this in the landing page of the app together with surveys conducted and surveys sent? Or do we want to keep this separate because we'll include graphs here below?

 [Link to buddybuild feedback from build 7](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=56dd05211be1540100399bf0&bnum=7)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/56dcafa10b8e3e0100d226ce/171ded52-cacc-4b6d-b5f2-da8115b855b8.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>7</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>100% Full</td></tr><tr><td>Memory free</td><td>335 MB / 1376 MB</td></tr></table>

**Comment by gtrsmith** [comment]
Lets keep it separate for now. I dont want to make too many major changes before we field test and this should not go on the landing page. The landing page will eventually have a lot of surveys on it - this will get crowded. The only individuals who will need to see this will know how to access with a little training
