### ISSUE TITLE
Sent/Unsent Summary

### ISSUE THREAD

**Issue by QISPSK** [EyeSeeTea/SurveillanceCambodiaApp#83]
Have the summary screen display only the following information:
1. Age
2. Gender
3. Species
4. Treatment (just type, not pills)

**Comment by ifoche** [comment]
And reason for not tested, isn't it?

**Comment by QISPSK** [comment]
Correct, my apologies, looks like that has been added in - thanks!

**Comment by QISPSK** [comment]
Also, just noticed that "Referral" is spelled incorrectly on the sent/unsent summary as the sub-consonant didn't register correctly. Should say: ធ្វើការបញ្ជូន
