### ISSUE TITLE
Image Attribution

### ISSUE THREAD

**Issue by QISPSK** [EyeSeeTea/SurveillanceCambodiaApp#84]
Change "Software Licenses" to just "Licenses"  (អជ្ញាប័ណ្ណ in Khmer, also updated in the translation file) and add the following attribution:
1. Pregnant by Andrew McKinley from the Noun Project
2. https://creativecommons.org/licenses/by/3.0/
3. Color of icon changed to white

**Comment by ifoche** [comment]
@rodmelia , @gtrsmith I think it's something that you have to decide. I'm assigning it to you waiting for your decision, and once decided, we can implement it

**Comment by QISPSK** [comment]
Relocated to "Backlog" as I don't see it in any of the sections of the application. Not really sure where it should be placed, however... Perhaps "About" or "Copyright"?

**Comment by ifoche** [comment]
I think I don't have much to say here. I suppose it's a task for @rbeccapotter,  @gtrsmith or @rodmelia to provide an updated legal text, and we can include it quickly. I'll wait for you to decide where to introduce it. Sorry if I moved it to "To test", we didn't really modify anything related to this, so it was a mistake.

**Comment by rbeccapotter** [comment]
@ifoche The attribution language is here (sorry, I don't think I sent you the link before): https://docs.google.com/document/d/1Sj6bVDV0oTx_4zcvKsgpEEaTkKBSXEPCpuSB0kfnvqY/edit

I think it belongs in the Legal --> Copyright section of the app.

**Comment by ifoche** [comment]
Thanks @rbeccapotter! we will incorporate it into next release
