### ISSUE TITLE
TO DELETE - clussiana@psi.org on build #28: Monitoring tab: data on DHA-PIP and AS/MQ are not updating…

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#85]
Feedback from clussiana@psi.org : Monitoring tab: data on DHA-PIP and AS/MQ are not updating correctly.

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/5760cc78a7d9390100574b08/d704deab-1101-4b25-a868-60d035e5c216.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>28</td></tr></table>

 [Link to buddybuild feedback from build 28](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=576113188931f20100b55b77&bnum=28)

**Comment by cristinaelle** [comment]
TO DELETE, thanks.

cristina
