### ISSUE TITLE
Skipping Questions

### ISSUE THREAD

**Issue by QISPSK** [EyeSeeTea/SurveillanceCambodiaApp#88]
If you're quick enough, you can skip proceeding screens by swiping to the left quickly after entering an answer. Is there a way to prevent this skip from within the app or enforce an answer to questions?

**Comment by ifoche** [comment]
Confirmed, it's a bug

**Comment by ifoche** [comment]
Can anyone confirm this is done?

**Comment by QISPSK** [comment]
@ifoche, I can confirm that I can no longer replicate this, however it appears that providers are still able to skip over questions and submit data. 

We visited a MMW yesterday who was able to submit a survey with just the RDT and gender screen filled out. He couldn't explain how it happened, but the survey did get sent to the server. We have since deleted it as he was simply testing the application and it wasn't real data.

We've also seen this crop up a few times during our pre- and post-tests during trainings, most notably under the KH MCS Pre-Test_RTK_01 OU. Again, providers couldn't quite explain how it happened. I will keep testing it here to see if I can replicate it.

**Comment by ifoche** [comment]
ok @QISPSK thanks for the efforts. I will try to replicate that too.

**Comment by ifoche** [comment]
@QISPSK I was not able to replicate this anymore...I'm moving to backlog just to keep an eye on it and if you see this again please report in order to let us go deeper and try to find out how can it happen.

**Comment by QISPSK** [comment]
@ifoche Will do. I think providers are no longer able to skip questions, but sometimes the data doesn't come though completely and it appears in DHIS2 as if the provider had skipped a question. Regardless, it is definitely something we will monitor going forward and let you know if it crops up again. Thanks!
