### ISSUE TITLE
Remove Ability to Change Font Size

### ISSUE THREAD

**Issue by QISPSK** [EyeSeeTea/SurveillanceCambodiaApp#90]
Can you please remove the ability to change the font size? The default font size works well (we haven't had any complaints so far) and the other font size options make the application difficult to use. A number of providers have accidentally turned on a different font size and have been unsure how to change it back.

**Comment by ifoche** [comment]
@QISPSK We've refactored the way we implemented the font sizes, can you please give it a try and let us know if it doesn't work as it is now?

**Comment by QISPSK** [comment]
![image](https://cloud.githubusercontent.com/assets/17549893/25211799/39caef6a-25b1-11e7-9b38-65267b56c148.png)

Moved back to "Backlog" as custom font sizes are not translated to Khmer. Translations are as follows: 

1.	Extra Small: តូចបំផុត
2.	Small: តូច
3.	Medium: មធ្យម
4.	Large: ធំ
5.	Extra Large: ធំបំផុត

**Comment by QISPSK** [comment]
Also, font size changes seem to only affect the question, not the answer, though I assume this has to do with the fact that the answer options are still images

**Comment by ifoche** [comment]
Yes, you're right, the questions cannot adapt to that font size because they are images. In that sense. If we go for using floating text on top of the options, that would be a bigger change. 

For the translations, you're also right, it seems we're not using the POEditor strings. Sorry for that. That's a quick fix. I use this last change to define the issue complexity label

**Comment by rodmelia** [comment]
We agreed not to use dynamic text for the answers- we tried before and the
solution was not satisfactory.

If we want to try again, we can do so in a future release, for which we
need to design a more elaborate solution and a new estimation

**Comment by QISPSK** [comment]
@ifoche and @rodmelia thanks for the explanations! @ifoche if you can go ahead and simply link these up with the POEditor translations, that would be great.

**Comment by ifoche** [comment]
Sure
