### ISSUE TITLE
Duplicate Data

### ISSUE THREAD

**Issue by QISPSK** [EyeSeeTea/SurveillanceCambodiaApp#96]
Hi all,

As mentioned in the email today, we are still seeing issues with duplicate data being sent by the newest version of the application (1.2.5). This issues was noticed at the most recent rollout training in Kep where we had serious issues with internet connectivity and while we can't quite replicate the issue here in Phnom Penh, we highly suspect that spotty internet coverage is to blame.

**Comment by QISPSK** [comment]
Hi all,

Just wanted to check on the status of this issue. It looks like it was moved to "Testing," is a duplicate data fix included in the newest BB version of the app? If so, we have yet to test this out. Let us know and we can do some trial runs to see if the issue has been fixed.

Thanks,
Eli

**Comment by ifoche** [comment]
Hi @QISPSK. Exactly. Last bb version incorporated a fix to solve the only source of duplicates we were able to find, so if you can test it and tell us if there's no duplicate anymore, that would be great. We're also now rewriting a piece of code that was not very clean (we call that "code refactoring"), so if we find any other potential source of duplicates we will notify you quickly.

**Comment by QISPSK** [comment]
Hi @ifoche. A quick test today revealed that duplicate data is still an issue on an intermittent internet connection so I have moved this issue back to "Ready" again. 

The two api links can be found here and are under the KH MCS Post-Test_BMC_01 OU: 
https://www.psi-mis.org/api/events/XwtHTmzF14L
https://www.psi-mis.org/api/events/xZVLkKEGJVp

Let me know if you have any questions.

Thanks,
Eli

**Comment by ifoche** [comment]
Hi @QISPSK, thanks for testing could you describe the process you followed to create the duplicate? I'm starting to blame to an eventual server side bug, but I want to replicate it myself if you can show me how.

**Comment by rodmelia** [comment]
It is hard for me to think that this is server side - we have a web app,
doing over 100k events per month, and we have never had duplicates...

**Comment by ifoche** [comment]
yes...but I'm sure that webapp doesn't have connectivity problems...right? It's installed on the same server? or even if it's different, probably its connection is not intermittent, right? I'm pretty sure that the API call action is quite atomic...so I wouldn't put all the eggs in that basket but I don't want to completely discard the idea

**Comment by QISPSK** [comment]
Hi @ifoche, in order to create the duplicates, I typically enter a large number of tests (~10 - 15 or so, mix of positive, negative, and not tested) while turning the WiFi on and off during the course of the tests. I think the duplicates come up when I successfully cut a full sync from happening (i.e, only 5 of the 10 unsent surveys send before I cut off the WiFi). I'd be happy to make a video of this process tomorrow if that would help clarify. Let me know if you have any questions!

**Comment by ifoche** [comment]
Hi @QISPSK just to let you know we've just found the source of duplicates originating those ones, when connection is intermittent. It was really hidden, but we've got it. Working on the solution that we've also already design so you will have a solution to test very soon.

**Comment by QISPSK** [comment]
@ifoche Excellent news! Looking forward to testing it out soon!

**Comment by ifoche** [comment]
@QISPSK. Now generating the new bb release with the solution to this problem. Hopefully it shouldn't crash on any device (even if it's 6.0). Please, let me know otherwise.

**Comment by QISPSK** [comment]
@ifoche After testing this out a handful of times, I cannot replicate the duplicate data issue! I've moved this issue to done and we'll keep  a close eye on this issue as soon as the newest version is released. Thanks!
